### ISSUE TITLE
Conflict: Inline editing / Roles - Edit...

### ISSUE THREAD

**Issue by eviweb** [karutaproject/karuta-frontend#107]
Dear all,    

there is a conflict between the `Inline Editing` setting and the two roles: `Roles - Edit Resource` and `Roles - Edit Label`.    
When the `Inline Editing` setting is enabled, an authorized editor cannot access the editing panel because the editing icon is hidden, except for the designer.
    
**Step to reproduce on a page:**    
As a designer:
* add a TextField or a Field item
* edit the created item and fill one or both if the roles text-fields mentioned previously
* check the `Inline Editing` checkbox
* click the refresh icon
* switch to the related role

**Actual result**    
the editing icon is hidden

**Expected result**
the editing icon is shown and the role can open the editing panel and get what he/she is allowed to edit

Best

Eric

**Comment by olivier-gerbe** [comment]
Done in 2.3

**Comment by isabelle-roy** [comment]
Olivier this is not resolved on the developement instances where I do the testing. 
I cannot close this issue until I see it resolved on savoie and eportfolium.fr

**Comment by isabelle-roy** [comment]
Tested and approved on our development instance.
